# -- PATHS
paths:
  base: "/content/drive/MyDrive/endo-immune-atlas"
  raw_data: "data/raw/GSE179640_Supp"
  raw_object:     "data/processed/GSE179640_raw.h5ad"
  qc_object:      "data/processed/GSE179640_qc.h5ad"
  integration_object:   "data/processed/GSE179640_integration.h5ad"
  cluster_object: "data/processed/GSE179640_total_clustering.h5ad"
  immune_object:  "data/processed/GSE179640_immune_subset.h5ad"
  sen_object:     "data/processed/GSE179640_senescence.h5ad"
  spatial_object: "data/processed/GSE179640_spatial.h5ad"
  results:        "results"
  preprocess_figs: "results/preprocessing"
  figures:        "results/figures"
  logs:           "logs"

# -- DATASET 
dataset:
  accession: "GSE179640"
  spatial_samples:
    - "GSM6690475"
    - "GSM6690476"
  exclude:
    - "EOR" # organoids
    - "EcPA" # ectopic adjacent

# -- QC
qc:
  min_genes: 500
  min_UMI: 1000
  max_UMI: 100000
  mt_threshold: 25
  min_cells: 3

# -- INTEGRATION
integration: 
  n_top_genes: 2000
  n_pcs: 50
  n_neighbors: 15

# -- CLUSTERING
total_clustering:
  resolution: 0.01
  logfoldthreshold: 1.5
  padj_threshold: 0.05

# -- IMMUNE SUBSET
# -- IMMUNOSENESCENCE
# -- SPATIAL
# -- COMMUNICATION